GET http://localhost:3000/users/659d210ff7261e407f351362

DELETE http://localhost:3000/users/65a040c03b59948749be8691
Content-Type: application/json

{
    "email": "testfor@example.com",
    "birthday": "Jan 30th",
    "favoriteColor": "Brown",
    "firstName": "Ismael",
    "lastName": "Barrowed"
}